apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CheckVolumes
metadata:
  name: check-allowed-volumes
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    - kube-system
    - ceph-csi-cephfs
  parameters:
    volumes:
    - "configMap"
    - "emptyDir"
    - "projected"
    - "secret"
    - "downwardAPI"
    - "persistentVolumeClaim"

