apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: checkvolumes 
spec:
  crd:
    spec:
      names:
        kind: CheckVolumes
      validation:
        openAPIV3Schema:
          properties:
            volumes:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package checkvolumes

        violation[{"msg": msg}] {
          volume_prepare := {x | input.review.object.spec.volumes[_][x]; x != "name"}
          volume_request := volume_prepare[_]
      
          not check_volumes(volume_request)
          msg := sprintf("Volume <%v> is not permitted", [volume_request])
        }

        check_volumes(volume_request) {
          volume_request == input.parameters.volumes[_]
        }

        check_volumes(volume_request) {
          input.parameters.volumes[_] == "*"
        }

