apiVersion: constraints.gatekeeper.sh/v1beta1
kind: checkpodrepo
metadata:
  name: private-repo-pod
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    repo: 
    - "private.com"
    - "cool.org"
