apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "sleep", "600"]
  containers:
    - name: web
      image: private.com/nginx:1.14
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
    - name: db
      image: mysql
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP

