apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: checkpodrepo 
spec:
  crd:
    spec:
      names:
        kind: checkpodrepo
      validation:
        openAPIV3Schema:
          properties:
            repo:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package checkpodrepo

        violation[{"msg": msg}] {
          containers := input.review.object.spec.containers[_]
          satisfied := [good | repo = input.parameters.repo[_] ; good = startswith(containers.image, repo)]
          not any(satisfied)

          msg := sprintf("Container image <%v> not in <%v> repo", [containers.image, input.parameters.repo])
        }

        violation[{"msg": msg}] {
          containers := input.review.object.spec.containers[_]
          satisfied := [good | repo = input.parameters.repo[_] ; good = startswith(containers.image, repo)]
          not any(satisfied)

          msg := sprintf("Container image <%v> not in <%v> repo", [containers.image, input.parameters.repo])
        }
